name: Node.js CI
<<<<<<< HEAD
on: push
jobs:
  build:
    runs-on: ubuntu-latest
=======
on: 
  push:
    # branches: [ master ]
  pull_request:
    # branches: [ master ]
env:
  TEST: test
  TEST2: test2
jobs:
  build:
    env:
      TEST: test_in_job

    runs-on: ubuntu-latest
    
    steps:
    - name: Use Node.js
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Set variable
      run: echo '::set-env name=TEST::in_step'
    - run: echo ${{ env.TEST }}
    - run: |
        npm ci
        npm run build --if-present
    - run: npm test
      if: ${{ success() }}
    - name: Login via Az module
      uses: azure/login@v1.1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: 'Deploy Azure Web App'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: nodeapp-training
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
